# Generated by Django 4.1.7 on 2023-05-03 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_customuser_service_address_delete_adresse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
